"""initial_schema

Revision ID: 470a95cdc5dc
Revises: 
Create Date: 2026-03-23 05:35:10.682660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '470a95cdc5dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('patients',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_tenant_id'), 'patients', ['tenant_id'], unique=False)
    op.create_table('clinical_encounters',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('provider_name', sa.String(length=200), nullable=False),
    sa.Column('date_of_service', sa.String(length=10), nullable=False),
    sa.Column('raw_notes', sa.Text(), nullable=True),
    sa.Column('raw_input_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_encounters_tenant_id'), 'clinical_encounters', ['tenant_id'], unique=False)
    op.create_table('insurance_plans',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('payer_name', sa.String(length=200), nullable=False),
    sa.Column('payer_id', sa.String(length=50), nullable=False),
    sa.Column('subscriber_id', sa.String(length=100), nullable=False),
    sa.Column('group_number', sa.String(length=100), nullable=False),
    sa.Column('plan_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_plans_tenant_id'), 'insurance_plans', ['tenant_id'], unique=False)
    op.create_table('clinical_procedures',
    sa.Column('encounter_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tooth_numbers', sa.JSON(), nullable=True),
    sa.Column('surfaces', sa.JSON(), nullable=True),
    sa.Column('quadrant', sa.String(length=20), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['clinical_encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_procedures_tenant_id'), 'clinical_procedures', ['tenant_id'], unique=False)
    op.create_table('coded_encounters',
    sa.Column('encounter_id', sa.Uuid(), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['clinical_encounters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('encounter_id')
    )
    op.create_index(op.f('ix_coded_encounters_tenant_id'), 'coded_encounters', ['tenant_id'], unique=False)
    op.create_table('claims',
    sa.Column('coded_encounter_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('provider_name', sa.String(length=200), nullable=False),
    sa.Column('date_of_service', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('primary_payer_name', sa.String(length=200), nullable=False),
    sa.Column('primary_payer_id', sa.String(length=50), nullable=False),
    sa.Column('primary_subscriber_id', sa.String(length=100), nullable=False),
    sa.Column('primary_group_number', sa.String(length=100), nullable=False),
    sa.Column('secondary_payer_name', sa.String(length=200), nullable=True),
    sa.Column('secondary_payer_id', sa.String(length=50), nullable=True),
    sa.Column('secondary_subscriber_id', sa.String(length=100), nullable=True),
    sa.Column('secondary_group_number', sa.String(length=100), nullable=True),
    sa.Column('preauth_required', sa.Boolean(), nullable=False),
    sa.Column('preauth_number', sa.String(length=50), nullable=True),
    sa.Column('preauth_status', sa.String(length=20), nullable=True),
    sa.Column('total_fee_submitted', sa.Float(), nullable=True),
    sa.Column('total_fee_allowed', sa.Float(), nullable=True),
    sa.Column('total_fee_paid', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coded_encounter_id'], ['coded_encounters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_tenant_id'), 'claims', ['tenant_id'], unique=False)
    op.create_table('coded_procedures',
    sa.Column('coded_encounter_id', sa.Uuid(), nullable=False),
    sa.Column('clinical_procedure_id', sa.Uuid(), nullable=False),
    sa.Column('cdt_code', sa.String(length=10), nullable=False),
    sa.Column('cdt_description', sa.Text(), nullable=False),
    sa.Column('tooth_number', sa.String(length=10), nullable=True),
    sa.Column('surfaces', sa.String(length=20), nullable=True),
    sa.Column('quadrant', sa.String(length=10), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('ai_reasoning', sa.Text(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=True),
    sa.Column('icd10_codes', sa.JSON(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('original_cdt_code', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinical_procedure_id'], ['clinical_procedures.id'], ),
    sa.ForeignKeyConstraint(['coded_encounter_id'], ['coded_encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coded_procedures_tenant_id'), 'coded_procedures', ['tenant_id'], unique=False)
    op.create_table('claim_attachments',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_attachments_tenant_id'), 'claim_attachments', ['tenant_id'], unique=False)
    op.create_table('claim_narratives',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('cdt_code', sa.String(length=10), nullable=False),
    sa.Column('narrative_text', sa.Text(), nullable=False),
    sa.Column('generated_by', sa.String(length=20), nullable=False),
    sa.Column('payer_tailored', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_narratives_tenant_id'), 'claim_narratives', ['tenant_id'], unique=False)
    op.create_table('claim_procedures',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('coded_procedure_id', sa.Uuid(), nullable=False),
    sa.Column('cdt_code', sa.String(length=10), nullable=False),
    sa.Column('cdt_description', sa.Text(), nullable=False),
    sa.Column('tooth_number', sa.String(length=10), nullable=True),
    sa.Column('surfaces', sa.String(length=20), nullable=True),
    sa.Column('quadrant', sa.String(length=10), nullable=True),
    sa.Column('fee_submitted', sa.Float(), nullable=True),
    sa.Column('fee_allowed', sa.Float(), nullable=True),
    sa.Column('fee_paid', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['coded_procedure_id'], ['coded_procedures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_procedures_tenant_id'), 'claim_procedures', ['tenant_id'], unique=False)
    op.create_table('denial_records',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('denial_reason_code', sa.String(length=20), nullable=False),
    sa.Column('denial_reason_description', sa.Text(), nullable=False),
    sa.Column('denied_amount', sa.Float(), nullable=True),
    sa.Column('payer_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_denial_records_tenant_id'), 'denial_records', ['tenant_id'], unique=False)
    op.create_table('era_records',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('payer_name', sa.String(length=200), nullable=False),
    sa.Column('payer_id', sa.String(length=50), nullable=False),
    sa.Column('payment_amount', sa.Float(), nullable=True),
    sa.Column('allowed_amount', sa.Float(), nullable=True),
    sa.Column('patient_responsibility', sa.Float(), nullable=True),
    sa.Column('adjustment_reason_codes', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('check_number', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_era_records_tenant_id'), 'era_records', ['tenant_id'], unique=False)
    op.create_table('submission_records',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('clearinghouse_name', sa.String(length=100), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('confirmation_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_submission_records_tenant_id'), 'submission_records', ['tenant_id'], unique=False)
    op.create_table('appeal_documents',
    sa.Column('denial_id', sa.Uuid(), nullable=False),
    sa.Column('appeal_text', sa.Text(), nullable=False),
    sa.Column('case_law_citations', sa.JSON(), nullable=True),
    sa.Column('supporting_evidence', sa.JSON(), nullable=True),
    sa.Column('generated_by', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['denial_id'], ['denial_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appeal_documents_tenant_id'), 'appeal_documents', ['tenant_id'], unique=False)
    op.create_table('commissioner_letters',
    sa.Column('denial_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('commissioner_name', sa.String(length=300), nullable=False),
    sa.Column('commissioner_address', sa.Text(), nullable=False),
    sa.Column('letter_text', sa.Text(), nullable=False),
    sa.Column('case_law_citations', sa.JSON(), nullable=True),
    sa.Column('mail_status', sa.String(length=20), nullable=False),
    sa.Column('mail_tracking_id', sa.String(length=100), nullable=True),
    sa.Column('trigger_type', sa.String(length=10), nullable=False),
    sa.Column('lob_letter_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['denial_id'], ['denial_records.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commissioner_letters_tenant_id'), 'commissioner_letters', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commissioner_letters_tenant_id'), table_name='commissioner_letters')
    op.drop_table('commissioner_letters')
    op.drop_index(op.f('ix_appeal_documents_tenant_id'), table_name='appeal_documents')
    op.drop_table('appeal_documents')
    op.drop_index(op.f('ix_submission_records_tenant_id'), table_name='submission_records')
    op.drop_table('submission_records')
    op.drop_index(op.f('ix_era_records_tenant_id'), table_name='era_records')
    op.drop_table('era_records')
    op.drop_index(op.f('ix_denial_records_tenant_id'), table_name='denial_records')
    op.drop_table('denial_records')
    op.drop_index(op.f('ix_claim_procedures_tenant_id'), table_name='claim_procedures')
    op.drop_table('claim_procedures')
    op.drop_index(op.f('ix_claim_narratives_tenant_id'), table_name='claim_narratives')
    op.drop_table('claim_narratives')
    op.drop_index(op.f('ix_claim_attachments_tenant_id'), table_name='claim_attachments')
    op.drop_table('claim_attachments')
    op.drop_index(op.f('ix_coded_procedures_tenant_id'), table_name='coded_procedures')
    op.drop_table('coded_procedures')
    op.drop_index(op.f('ix_claims_tenant_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_coded_encounters_tenant_id'), table_name='coded_encounters')
    op.drop_table('coded_encounters')
    op.drop_index(op.f('ix_clinical_procedures_tenant_id'), table_name='clinical_procedures')
    op.drop_table('clinical_procedures')
    op.drop_index(op.f('ix_insurance_plans_tenant_id'), table_name='insurance_plans')
    op.drop_table('insurance_plans')
    op.drop_index(op.f('ix_clinical_encounters_tenant_id'), table_name='clinical_encounters')
    op.drop_table('clinical_encounters')
    op.drop_index(op.f('ix_patients_tenant_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
