"""Seed data for CDT code reference database.

Contains ~40 commonly used CDT codes across major categories with realistic
metadata for AI-assisted dental coding. Descriptions are abbreviated summaries
(not ADA-copyrighted official descriptors).
"""

from __future__ import annotations

# Each entry is a tuple:
# (code, description, category, subcategory,
#  common_scenarios, confused_with, bundling_notes, frequency_notes,
#  narrative_required, common_denial_reasons)

SEED_CDT_CODES: list[tuple] = [
    # ── Diagnostic ──────────────────────────────────────────────────────
    (
        "D0120",
        "Periodic oral evaluation - established patient",
        "diagnostic",
        "evaluation",
        ["routine recall exam", "periodic checkup for existing patient"],
        ["D0150"],
        "Typically bundled with prophylaxis visit",
        "Usually limited to 2x per 12 months",
        False,
        ["exceeds frequency limit", "billed with comprehensive eval same date"],
    ),
    (
        "D0140",
        "Limited oral evaluation - problem focused",
        "diagnostic",
        "evaluation",
        ["emergency toothache visit", "evaluation of specific complaint"],
        ["D0120", "D0170"],
        "",
        "Not frequency limited but must document specific problem",
        False,
        ["no documentation of specific problem", "billed same day as periodic eval"],
    ),
    (
        "D0150",
        "Comprehensive oral evaluation - new or established patient",
        "diagnostic",
        "evaluation",
        ["new patient comprehensive exam", "comprehensive re-evaluation"],
        ["D0120", "D0180"],
        "",
        "Usually 1x per 36 months for same provider",
        False,
        ["frequency limitation", "not a new patient"],
    ),
    (
        "D0180",
        "Comprehensive periodontal evaluation - new or established patient",
        "diagnostic",
        "evaluation",
        ["perio evaluation with probing depths", "full periodontal charting"],
        ["D0150"],
        "",
        "Usually 1x per 36 months",
        True,
        ["no perio charting documented", "used for non-perio patient"],
    ),
    (
        "D0210",
        "Intraoral - complete series of radiographic images",
        "diagnostic",
        "radiograph",
        ["full mouth x-rays", "FMX radiographic series"],
        ["D0330"],
        "Should not be billed with panoramic same date",
        "Usually 1x per 36 months",
        False,
        ["frequency limitation", "billed with panoramic same date"],
    ),
    (
        "D0220",
        "Intraoral - periapical first radiographic image",
        "diagnostic",
        "radiograph",
        ["single PA x-ray", "periapical radiograph of tooth"],
        ["D0230"],
        "First PA only; additional PAs use D0230",
        "",
        False,
        ["should be D0230 for additional images"],
    ),
    (
        "D0230",
        "Intraoral - periapical each additional radiographic image",
        "diagnostic",
        "radiograph",
        ["additional PA x-ray", "second or subsequent periapical image"],
        ["D0220"],
        "Requires D0220 on same date; not standalone",
        "",
        False,
        ["billed without D0220", "exceeds reasonable number"],
    ),
    (
        "D0272",
        "Bitewings - two radiographic images",
        "diagnostic",
        "radiograph",
        ["two bitewing x-rays", "right and left posterior bitewings"],
        ["D0274"],
        "",
        "Usually 2x per 12 months",
        False,
        ["frequency limitation", "billed with four BWs same date"],
    ),
    (
        "D0274",
        "Bitewings - four radiographic images",
        "diagnostic",
        "radiograph",
        ["four bitewing x-rays", "full set of bitewing radiographs"],
        ["D0272"],
        "",
        "Usually 2x per 12 months (combined with D0272)",
        False,
        ["frequency limitation", "downcode to two BWs"],
    ),
    (
        "D0330",
        "Panoramic radiographic image",
        "diagnostic",
        "radiograph",
        ["panorex", "panoramic x-ray"],
        ["D0210"],
        "Should not be billed with FMX same date",
        "Usually 1x per 36 months",
        False,
        ["frequency limitation", "billed with FMX same date"],
    ),
    # ── Preventive ──────────────────────────────────────────────────────
    (
        "D1110",
        "Prophylaxis - adult",
        "preventive",
        "prophylaxis",
        ["adult teeth cleaning", "routine prophylaxis for adult patient"],
        ["D4910", "D1120"],
        "Cannot bill same date as D4910",
        "Usually 2x per 12 months",
        False,
        ["exceeds frequency", "patient has perio history should be D4910"],
    ),
    (
        "D1120",
        "Prophylaxis - child",
        "preventive",
        "prophylaxis",
        ["child teeth cleaning", "prophylaxis for patient under 14"],
        ["D1110"],
        "",
        "Usually 2x per 12 months",
        False,
        ["patient age exceeds child limit", "exceeds frequency"],
    ),
    (
        "D1206",
        "Topical application of fluoride varnish",
        "preventive",
        "fluoride",
        ["fluoride varnish application", "in-office fluoride treatment"],
        ["D1208"],
        "Cannot bill with D1208 same date",
        "Usually 2x per 12 months; some payers age-limited",
        False,
        ["exceeds frequency", "patient over age limit", "billed with D1208"],
    ),
    (
        "D1351",
        "Sealant - per tooth",
        "preventive",
        "sealant",
        ["pit and fissure sealant", "dental sealant on molar"],
        [],
        "",
        "Usually 1x per tooth per 36 months; age limited to under 16",
        False,
        ["patient over age limit", "tooth already has restoration", "tooth previously sealed"],
    ),
    # ── Restorative ─────────────────────────────────────────────────────
    (
        "D2140",
        "Amalgam - one surface, primary or permanent",
        "restorative",
        "amalgam",
        ["one surface amalgam filling", "single surface silver filling"],
        ["D2330"],
        "",
        "",
        False,
        ["surface count mismatch", "tooth already restored"],
    ),
    (
        "D2150",
        "Amalgam - two surfaces, primary or permanent",
        "restorative",
        "amalgam",
        ["two surface amalgam filling", "MO or DO amalgam"],
        ["D2331"],
        "",
        "",
        False,
        ["surface count mismatch", "downcode to one surface"],
    ),
    (
        "D2160",
        "Amalgam - three surfaces, primary or permanent",
        "restorative",
        "amalgam",
        ["three surface amalgam filling", "MOD amalgam"],
        ["D2332", "D2393"],
        "",
        "",
        False,
        ["surface count mismatch", "downcode to two surfaces"],
    ),
    (
        "D2330",
        "Resin-based composite - one surface, anterior",
        "restorative",
        "composite",
        ["one surface anterior composite", "single surface tooth-colored filling front tooth"],
        ["D2140"],
        "",
        "",
        False,
        ["surface count mismatch"],
    ),
    (
        "D2331",
        "Resin-based composite - two surfaces, anterior",
        "restorative",
        "composite",
        ["two surface anterior composite", "two surface tooth-colored filling front tooth"],
        ["D2150"],
        "",
        "",
        False,
        ["surface count mismatch", "downcode to one surface"],
    ),
    (
        "D2332",
        "Resin-based composite - three surfaces, anterior",
        "restorative",
        "composite",
        ["three surface anterior composite", "three surface tooth-colored filling front tooth"],
        ["D2160"],
        "",
        "",
        False,
        ["surface count mismatch", "downcode to two surfaces"],
    ),
    (
        "D2391",
        "Resin-based composite - one surface, posterior",
        "restorative",
        "composite",
        ["one surface posterior composite", "single surface tooth-colored filling back tooth"],
        ["D2140"],
        "Some payers downcode to amalgam",
        "",
        False,
        ["downcode to amalgam", "surface count mismatch"],
    ),
    (
        "D2392",
        "Resin-based composite - two surfaces, posterior",
        "restorative",
        "composite",
        ["two surface posterior composite", "MO or DO composite back tooth"],
        ["D2150"],
        "Some payers downcode to amalgam",
        "",
        False,
        ["downcode to amalgam", "surface count mismatch"],
    ),
    (
        "D2393",
        "Resin-based composite - three surfaces, posterior",
        "restorative",
        "composite",
        ["three surface composite posterior", "MOD composite"],
        ["D2160"],
        "Some payers downcode to amalgam",
        "",
        False,
        ["downcode to amalgam", "surface count mismatch"],
    ),
    (
        "D2394",
        "Resin-based composite - four or more surfaces, posterior",
        "restorative",
        "composite",
        ["four surface posterior composite", "four+ surface composite back tooth"],
        [],
        "Some payers downcode to amalgam",
        "",
        False,
        ["downcode to amalgam", "consider crown instead"],
    ),
    (
        "D2740",
        "Crown - porcelain/ceramic substrate",
        "restorative",
        "crown",
        ["all-ceramic crown", "porcelain crown", "emax crown"],
        ["D2750"],
        "D2950 core buildup often denied same date",
        "Usually 1x per tooth per 60 months",
        True,
        ["frequency limitation", "missing documentation of necessity", "buildup denied"],
    ),
    (
        "D2750",
        "Crown - porcelain fused to high noble metal",
        "restorative",
        "crown",
        ["PFM crown", "porcelain fused to metal crown"],
        ["D2740"],
        "D2950 core buildup often denied same date",
        "Usually 1x per tooth per 60 months",
        False,
        ["frequency limitation", "missing documentation of necessity"],
    ),
    (
        "D2950",
        "Core buildup, including any pins when required",
        "restorative",
        "crown",
        ["core buildup under crown", "buildup for crown preparation"],
        [],
        "Often bundled/denied with crown; must document necessity separately",
        "",
        True,
        ["bundled with crown", "insufficient documentation", "tooth not broken down enough"],
    ),
    # ── Endodontics ─────────────────────────────────────────────────────
    (
        "D3310",
        "Endodontic therapy, anterior tooth",
        "endodontics",
        "root_canal",
        ["root canal anterior tooth", "root canal on front tooth"],
        ["D3320"],
        "",
        "",
        True,
        ["missing pre-op radiograph", "missing diagnosis"],
    ),
    (
        "D3320",
        "Endodontic therapy, premolar tooth",
        "endodontics",
        "root_canal",
        ["root canal premolar", "root canal on bicuspid"],
        ["D3310", "D3330"],
        "",
        "",
        True,
        ["wrong tooth type", "missing pre-op radiograph"],
    ),
    (
        "D3330",
        "Endodontic therapy, molar tooth",
        "endodontics",
        "root_canal",
        ["root canal molar", "root canal on back tooth"],
        ["D3320"],
        "",
        "",
        True,
        ["missing pre-op radiograph", "missing diagnosis", "retreatment should be D3346-D3348"],
    ),
    # ── Periodontics ────────────────────────────────────────────────────
    (
        "D4341",
        "Periodontal scaling and root planing - four or more teeth per quadrant",
        "periodontics",
        "srp",
        ["deep cleaning quadrant 4+ teeth", "scaling and root planing"],
        ["D4342", "D1110"],
        "Cannot bill with prophylaxis same date",
        "Usually 1x per quadrant per 24 months",
        True,
        ["missing perio charting", "insufficient pocket depths", "billed with prophy"],
    ),
    (
        "D4342",
        "Periodontal scaling and root planing - one to three teeth per quadrant",
        "periodontics",
        "srp",
        ["deep cleaning quadrant 1-3 teeth", "limited SRP"],
        ["D4341"],
        "Cannot bill with prophylaxis same date",
        "Usually 1x per quadrant per 24 months",
        True,
        ["missing perio charting", "should be D4341 if 4+ teeth"],
    ),
    (
        "D4910",
        "Periodontal maintenance",
        "periodontics",
        "maintenance",
        ["perio maintenance cleaning", "periodontal maintenance after SRP"],
        ["D1110"],
        "Cannot bill same date as D1110",
        "Usually 4x per 12 months; requires prior SRP history",
        False,
        ["no history of active perio treatment", "billed as prophy instead"],
    ),
    # ── Oral Surgery ────────────────────────────────────────────────────
    (
        "D7140",
        "Extraction, erupted tooth or exposed root",
        "oral_surgery",
        "extraction",
        ["simple extraction", "routine tooth extraction"],
        ["D7210"],
        "",
        "",
        False,
        ["should be surgical extraction D7210"],
    ),
    (
        "D7210",
        "Extraction, erupted tooth requiring removal of bone and/or sectioning",
        "oral_surgery",
        "extraction",
        ["surgical extraction", "extraction with bone removal"],
        ["D7140", "D7220"],
        "",
        "",
        True,
        ["insufficient documentation of surgical need", "downcode to D7140"],
    ),
    (
        "D7220",
        "Removal of impacted tooth - soft tissue",
        "oral_surgery",
        "impaction",
        ["soft tissue impacted tooth removal", "soft tissue impaction extraction"],
        ["D7210", "D7230"],
        "",
        "",
        True,
        ["radiograph does not confirm impaction level"],
    ),
    (
        "D7230",
        "Removal of impacted tooth - partially bony",
        "oral_surgery",
        "impaction",
        ["partially bony impacted tooth removal", "partial bony impaction"],
        ["D7220", "D7240"],
        "",
        "",
        True,
        ["radiograph does not confirm impaction level", "downcode to soft tissue"],
    ),
    (
        "D7240",
        "Removal of impacted tooth - completely bony",
        "oral_surgery",
        "impaction",
        ["completely bony impacted tooth removal", "full bony impaction"],
        ["D7230"],
        "",
        "",
        True,
        ["radiograph does not confirm impaction level", "downcode to partially bony"],
    ),
    # ── Prosthodontics ──────────────────────────────────────────────────
    (
        "D5110",
        "Complete denture - maxillary",
        "prosthodontics",
        "denture",
        ["upper complete denture", "full upper denture"],
        ["D5120"],
        "",
        "Usually 1x per 60 months",
        False,
        ["frequency limitation", "missing documentation of edentulous arch"],
    ),
    (
        "D5120",
        "Complete denture - mandibular",
        "prosthodontics",
        "denture",
        ["lower complete denture", "full lower denture"],
        ["D5110"],
        "",
        "Usually 1x per 60 months",
        False,
        ["frequency limitation", "missing documentation of edentulous arch"],
    ),
    # ── Adjunctive ──────────────────────────────────────────────────────
    (
        "D9110",
        "Palliative treatment of dental pain - minor procedure",
        "adjunctive",
        "palliative",
        ["emergency pain treatment", "palliative care for toothache"],
        ["D0140"],
        "May be bundled with definitive treatment same date",
        "",
        True,
        ["bundled with definitive treatment", "insufficient documentation"],
    ),
    (
        "D9230",
        "Inhalation of nitrous oxide / analgesia, anxiolysis",
        "adjunctive",
        "anesthesia",
        ["nitrous oxide sedation", "laughing gas during procedure"],
        [],
        "",
        "",
        False,
        ["not covered benefit", "no supporting procedure"],
    ),
]
